# Generated by Django 5.1.3 on 2024-11-05 20:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_data_app', '0004_task_user_tasks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='tasks',
        ),
        migrations.AddField(
            model_name='task',
            name='user',
            field=models.ManyToManyField(blank=True, null=True, related_name='task', to=settings.AUTH_USER_MODEL),
        ),
    ]
