# Generated by Django 5.1.3 on 2024-11-05 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_data_app', '0007_alter_task_user_alter_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
