# Generated by Django 5.1.3 on 2024-11-05 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_data_app', '0009_remove_task_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
