# Generated by Django 5.1.3 on 2024-11-05 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_data_app', '0010_task_priority'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=30)),
                ('color', models.CharField(blank=True, default='', max_length=15)),
                ('name_tag', models.CharField(blank=True, default='', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='SubTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=30)),
                ('checked', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='task',
            name='category',
        ),
        migrations.AddField(
            model_name='task',
            name='subtask',
            field=models.ManyToManyField(blank=True, related_name='task', to='task_data_app.subtask'),
        ),
        migrations.AddField(
            model_name='task',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='task', to='task_data_app.category'),
        ),
    ]
