# Generated by Django 5.1.3 on 2024-11-05 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_data_app', '0011_category_subtask_remove_task_category_task_subtask_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
    ]
