# Generated by Django 5.1.3 on 2024-12-08 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_data_app', '0013_alter_subtask_name_alter_task_priorityimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(blank=True, default='', max_length=30, unique=True),
        ),
    ]
