# Generated by Django 5.1.3 on 2024-12-22 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_data_app', '0014_alter_category_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='subtask',
        ),
        migrations.AddField(
            model_name='task',
            name='subtask',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task', to='task_data_app.subtask'),
        ),
    ]
